# netlify.toml

[build]
  command = "npm run build" # คำสั่งสำหรับ Build Frontend ของคุณ (จาก package.json)
  publish = "dist"          # โฟลเดอร์ที่ Vite Build Frontend ออกมา

[functions]
  directory = "netlify/functions" # โฟลเดอร์สำหรับ Serverless Functions ของคุณ
  # node_bundler = "esbuild"      # (Optional) หากต้องการใช้ bundler อื่นสำหรับ functions
  # external_node_modules = ["node-fetch"] # (Optional) ถ้า function ใช้ external modules บางตัวที่ Netlify ไม่ได้ bundler ให้อัตโนมัติ

# ตัวอย่างการตั้งค่า Redirects (เช่น สำหรับ Single Page Applications)
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200